name: flutter_flex_panels
description: "A new Flutter package project."
version: 1.0.0-alpha.1
homepage: https://github.com/dipdev-studio/flutter_flex_panels
issue_tracker: https://github.com/dipdev-studio/flutter_flex_panels/issues
repository: https://github.com/dipdev-studio/flutter_flex_panels

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

funding:
  - https://www.buymeacoffee.com/example_user
  - https://www.patreon.com/some-account

screenshots:
  - description: "This screenshot shows the transformation of a number of bytes"
    path: assets/blank.webp

topics:
  - ui
  - widgets
  - flutter
  - layout
